#!/usr/bin/env python3



import os, re, shlex, operator, argparse, glob, warnings
import numpy as np
import pandas as pd
from functools import reduce
from collections import defaultdict
import subprocess
from concurrent.futures import ThreadPoolExecutor
import joblib
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
import torch
from torch.utils.data import Dataset
import torch.nn as nn
from torch.utils.data import DataLoader
from sklearn.compose import ColumnTransformer
from torch.utils.data import Sampler, RandomSampler, SequentialSampler
from GVHoP_NN import MetaDataset
from GVHoP_NN import MetaNN
from GVHoP_NN import SafeBatchSampler


"""
########################################
## Giant Virus-Host Predictor (GVHoP) ##
########################################
GVHoP.py
v1 2026

Author: Hsin-Ying Chang
Email: hyhazelchang@gmail.com

Usage:
chmod u+x GVHoP.py
./GVHoP.py --in_dir=example_MAGs/ --in_file_ext=faa --db_dir=GVHoP_database_v1.0/ --sample_ls=source_data/example_inputs/sample.ls --out_dir=gvhop_out/ --cpu=20

GVHoP --in_dir=example_MAGs/ --in_file_ext=faa --db_dir=GVHoP_database_v1.0/ --sample_ls=source_data/example_inputs/sample.ls --out_dir=gvhop_out/ --cpu=20

# Before running the GVHoP.py, please make sure to download the database, pre-trained models and check directory in GVHoP.py.
"""

def cmd_hmmer(in_dir, in_file_ext, out_dir, db_dir, cpu):
    in_files = glob.glob(in_dir + "*." + in_file_ext)
    count = 0
    hmm_cmd = []
    os.makedirs(f"{out_dir}hmmsearch/", exist_ok=True)
    for file in in_files:
        count += 1
        file_name = file.replace(in_dir, "")
        file_name = file_name.replace(f".{in_file_ext}", "")
        hmm_cmd.append(f"hmmsearch --cpu {cpu} -E 1e-5 --domtblout {out_dir}hmmsearch/{file_name}.domout {db_dir}/GVHoP_GVOGs.hmm {file}")
    return hmm_cmd

def cmd_diamond(in_dir, in_file_ext, out_dir, db_dir, cpu):
    in_files = glob.glob(in_dir + "*." + in_file_ext)
    count = 0
    diamond_cmd = []
    os.makedirs(f"{out_dir}diamond_blastp/", exist_ok=True)
    for file in in_files:
        count += 1
        file_name = file.replace(in_dir, "")
        file_name = file_name.replace(f".{in_file_ext}", "")
        diamond_cmd.append(f"diamond blastp -d {db_dir}/GVHoP_GVEUKs.dmnd -q {file} -o {out_dir}diamond_blastp/{file_name}.txt -f 6 -p {cpu} --evalue 1e-5")
    return diamond_cmd

def execute_cmd(cmd, job_name):
    os.makedirs("execute/", exist_ok=True)
    log_file = f"execute/{job_name}.log"
    cmd_list = shlex.split(cmd)
    print(f"Running: {cmd}\n")
    subprocess.run(cmd_list, stdout=open(log_file, "w"), stderr=subprocess.STDOUT, check=True)

def run_jobs(cmd, job_name):
    with ThreadPoolExecutor(max_workers=4) as executor:
        executor.map(lambda c: execute_cmd(c, job_name), cmd)

def hmmparser(hmmer_in):
	hits = []
	bit_dict = {}
	content_dict = defaultdict(dict)
	for filenames in os.listdir(hmmer_in):
		if filenames.endswith("domout"):
			acc = re.sub('.' + "domout", "", filenames)
			f = open(hmmer_in + "/" + filenames, 'r')
			o = open(hmmer_in + "/" + filenames + ".parsed", 'w')
			o.write("protein_id\taccession\tbest_hit\taln_start\taln_end\tscore\ttype\n")
			hit_dict = {}
			start_dict = {}
			end_dict = {}
			bit_dict = defaultdict(int)
			position_dict = defaultdict(list)
			for line in f.readlines():
				if line.startswith("#"):
					pass
				else:
					newline = re.sub(r'\s+', '\t', line)
					list1 = newline.split('\t')
					ids = list1[0]
					hit = re.sub("_", "", list1[3])
					#print(hit)
					score = float(list1[7])
					domain_evalue = float(list1[11])
					if score > bit_dict[ids] and domain_evalue < 1e-3:
						ids_hit = ids +"."+ hit
						start = int(list1[15])
						end   = int(list1[16])
						position_dict[ids_hit].append(start)
						position_dict[ids_hit].append(end)
						#print(ids_hit, score, domain_evalue, start, end)
						hit_dict[ids] = hit
						start_dict[ids] = start
						end_dict[ids] = end
						bit_dict[ids] = score
			bit_sorted = sorted(bit_dict.items(), key=operator.itemgetter(1), reverse=True)
			output_list = []
			for item in bit_sorted:
				entry = item[0]
				score = item[1]
				if score > 0:
					#print entry, item, filenames
					ids_hit = entry + "." + hit_dict[entry]
					output_list.append(entry +"\t"+ str(hit_dict[entry]) +"\t"+ str(min(position_dict[ids_hit])) +"\t"+ str(max(position_dict[ids_hit])) +"\t"+ str(bit_dict[entry]) )
			done = []
			for line in output_list:
				line1 = line.rstrip()
				tabs = line1.split("\t")
				ids = tabs[0]
				hits.append(ids)
				cog = tabs[1]
				start = tabs[2]
				end = tabs[3]
				aln_length = str(abs(float(end) - float(start)))
				score = tabs[4]
				nr = acc + "_" + cog
				if nr in done:
					content_dict[acc][cog] += 1
					o.write(ids +"\t"+ acc +"\t"+ cog +"\t"+ start +"\t"+ end +"\t"+ aln_length +"\t"+ score +"\tNH\n")
				else:
					content_dict[acc][cog] = 1
					o.write(ids +"\t"+ acc +"\t"+ cog +"\t"+ start +"\t"+ end +"\t"+ aln_length +"\t"+ score +"\tBH\n")
					done.append(nr)
			o.close()
	return content_dict

def blastparser(blast_in):
	# Read data from input files
    blastfiles = [filename for filename in os.listdir(blast_in) if filename.endswith("txt")]
    # Check presence/absence of hits
    score_dict = defaultdict(dict)
    for file in blastfiles:
        filename = os.path.basename(file).replace('.'+ "txt", '')
        try:
            result = pd.read_csv(os.path.join(blast_in, file), sep='\t')
        except pd.errors.EmptyDataError:
            result = pd.DataFrame()
        if not result.empty:
            hits = result.iloc[:, 1].to_list()
            for i in range(len(hits)):
                if filename in score_dict[hits[i]].keys():
                    if result.iloc[i, 11] > score_dict[hits[i]][filename]:
                        score_dict[hits[i]][filename] = result.iloc[i, 11]
                else:
                    score_dict[hits[i]][filename] = result.iloc[i, 11]
    return score_dict

def xgb_gpu_available():
    try:
        model = xgb.XGBClassifier(tree_method="hist", device="cuda")
        X_dummy = np.array([[1]])
        y_dummy = np.array([1])
        model.fit(X_dummy, y_dummy)
        return True
    except Exception:
        return False
    
def run_XGBclf(data_df, scaler_col, model, prob_out, hosts):
    # Load new data (unlabeled)
    X_test = data_df.to_numpy()
    X_test_final = []
    for i, scaler in enumerate(model.named_steps['scalers']):
        X_block = X_test[:, i*scaler_col:(i+1)*scaler_col]
        X_block_scaled = scaler.transform(X_block)
        X_test_final.append(X_block_scaled)
    X_test_scaled = np.concatenate(X_test_final, axis=1)
    if xgb_gpu_available():
        feature_selector = model.named_steps['feature_selector']
        clf = model.named_steps['classifier']
    else:
        feature_selector = model.named_steps['feature_selector']
        clf = model.named_steps['classifier']
        feature_selector.set_params(estimator__device="cpu", estimator__n_jobs=-1)
        clf.set_params(device="cpu", n_jobs=-1)
    X_test_selected = feature_selector.transform(X_test_scaled)
    y_scores = clf.predict(X_test_selected, output_margin=True)
    prob_out_new = pd.concat([prob_out.reset_index(drop=True), 
                              pd.DataFrame(y_scores, columns = hosts).reset_index(drop=True)], 
                              axis=1)
    return prob_out_new

def aggregate_prob(probs, node_dict, node_name):
    return sum(probs[i] for i in node_dict[node_name])

def climbing_inference(prob_tb, hierarch_list, node_dict, threshold):
    """
    Function for climbing inference for HSC
    # ex: test_label: 2130 (from most specific → most general)
    # pred_label: --30 (from most specific → most general)
    # from predicted leaf to root
    """
    # ----------------------------
    # Reverse the hierarch from most specific → most general
    # ----------------------------
    rev_hierarch_list = [sublist[::-1] for sublist in hierarch_list]

    # ----------------------------
    # Define correct answers
    # ----------------------------
    prob_out_levels = {}
    prob_out_levels["testset"] = prob_tb["testset"].to_list()
    # prob_out_levels["test_label"] = [[x] for x in prob_tb["test_label"].to_list()]
    y_pred = prob_tb["pred_label"].to_numpy()
    y_predpr = prob_tb.iloc[:, 2:].to_numpy()

    hierarch_dict = {}
    for i in range(len(hierarch_list[0])):
        labels = sorted({sublist[i] for sublist in rev_hierarch_list})
        hierarch_dict[f"level{i}"] = labels
    # ----------------------------
    # Climbing inference rule with threshold
    # ----------------------------
    prob_out_levels["pred_label"] = []
    prob_out_levels["pred_hierarchy"] = []
    for i in range(len(hierarch_list[0])):
        prob_out_levels[f"level{i}_prob"] = []

    for j in range(len(y_pred)):
        pred_l = y_pred[j] # predicted label: 0, 1, 2...
        predpr = y_predpr[j] # probabilities of predictions
        prediction = hierarch_dict["level0"][pred_l] # predicted name
        hierach_of_pred_l = [item for sublist in rev_hierarch_list if prediction in sublist for item in sublist] # hierarch of predicted label
        pred_label_index = []
        pred_label_hierarch = []
        # climbing
        for h in range(len(hierach_of_pred_l)):
            p = aggregate_prob(predpr, node_dict, hierach_of_pred_l[h])
            if p >= threshold:
                prob_out_levels[f"level{h}_prob"].append(p)
                pr = hierarch_dict[f"level{h}"].index(hierach_of_pred_l[h])
                pred_label_index.append(str(pr))
                pred_label_hierarch.append(hierach_of_pred_l[h])
            else:
                prob_out_levels[f"level{h}_prob"].append("-")
                pred_label_index.append("-")
                pred_label_hierarch.append("-")
        prob_out_levels["pred_label"].append(",".join(pred_label_index))
        prob_out_levels["pred_hierarchy"].append(",".join(pred_label_hierarch))
    df = pd.DataFrame(prob_out_levels)
    return df

def count_predictions_BU(prob_tb, all_pred, samples_pred):
    """Count hierarchy outputs"""
    pred_roots = 0
    test_ids = prob_tb["testset"].to_list()
    pred_label = [h.split(",") for h in prob_tb["pred_label"].to_list()]
    pred_hierarch = [h.split(",") for h in prob_tb["pred_hierarchy"].to_list()]
    for i in range(len(pred_label)):
        id = test_ids[i]
        for j in range(len(pred_label[0])):
            if pred_hierarch[i][j] != "-":			
                for k in range(j, len(pred_label[0])):
                    samples_pred[id][k][pred_hierarch[i][k]] += 1
                all_pred[id][pred_hierarch[i][k]] += 1
                break
            elif j == len(pred_label[0]) - 1:
                all_pred[id]["root"] += 1
                pred_roots += 1

def flatten_nested(lst):
    flattened_lst = []
    for item in lst:
        if isinstance(item, list):
            for subitem in flatten_nested(item):
                if subitem not in flattened_lst:
                    flattened_lst.append(subitem)
        else:
            if item not in flattened_lst:
                flattened_lst.append(item)
    return flattened_lst    

def main():
    parser = argparse.ArgumentParser(
            description=("Giant Virus-Host Predictor"),
            formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--in_dir",
                        type=str,
                        default="../example_MAGs/",
                        help="The directory of input files.")
    parser.add_argument("--in_file_ext",
                        required=True,
                        default="faa",
                        type=str)
    parser.add_argument("--sample_ls",
                        type=str,
						required=True,
                        default="./source_data/example_inputs/sample.ls",
                        help="The list of samples to be predicted.")
    parser.add_argument("--db_dir",
                        default="GVHoP_database_v1.0/",
                        required=True,
                        type=str,
                        help="Directory containing database files.")
    parser.add_argument("--out_dir",
                        type=str,
						required=True,
                        default='./outdir/',
                        help="The directory for output files.") 
    parser.add_argument("--cpu",
                        type=str,
						required=True,
                        default='8',
                        help="The number of CPU cores to use.") 
    
    # Defining variables from input
    args = parser.parse_args()
    in_dir = args.in_dir
    in_file_ext = args.in_file_ext
    sample_ls = [line.strip() for line in open(args.sample_ls, "r")]
    db_dir = args.db_dir
    out_dir = args.out_dir
    cpu = args.cpu

    """ Prepare host lists """    
    top_ls = ['Algae', 'Amoeba', 'Fungi', 'Heteroflagellate', 'Metazoa']
    intermediate_ls = ['Amoeboid', 'Amoebozoa', 'Blastocladiomycota', 'Brownalgae', 'Chlorophyta', 'Chytridiomycota', 'Haptophyta', 'Invertebrate', 'Nonamoeboid', 'Otheralgae', 'Vertebrate']
    bottom_ls = ['Aves', 'Bathycoccaceae', 'Blastocladiomycetes', 'Chlorellaceae', 'Choanocafe', 'Chytridiomycetes', 'Coccolithophyceae', 'Discoba', 'Discosea', 'Insecta', 'Malacostraca', 'Mamiellaceae', 'Mammalia', 'Otherchlorophyta', 'Otherhaptophyta', 'Otherinvertebrate', 'Othervertebrate', 'Phaeophyceae', 'Prymnesiaceae', 'Stramenopile', 'Tubulinea']

    """ Create output directory """
    os.makedirs(out_dir, exist_ok=True)

    """ Run Diamond and HMMER """
    print("Running Diamond and HMMER...")
    hmmer_cmd = cmd_hmmer(in_dir, in_file_ext, out_dir, db_dir, cpu)
    diamond_cmd = cmd_diamond(in_dir, in_file_ext, out_dir, db_dir, cpu)
    with ThreadPoolExecutor(max_workers=8) as executor:
        executor.submit(run_jobs(diamond_cmd, "diamond_blastp"))
        executor.submit(run_jobs(hmmer_cmd, "hmmer"))
    print("Finished running Diamond and HMMER!")

    """ Parse results """
    print("Parsing results...")
    hmm_dict = hmmparser(f"{out_dir}hmmsearch/")
    blast_dict = blastparser(f"{out_dir}diamond_blastp/")

    # Combine all rows into a DataFrame
    hmm_df = pd.DataFrame(hmm_dict)
    blast_df = pd.DataFrame(blast_dict)
    hmm_df = hmm_df.fillna(0).astype(int)
    blast_df = blast_df.fillna(0).astype(int)
    hmm_df.columns = hmm_df.columns.astype(str)
    blast_df.columns = blast_df.columns.astype(str)
    hmm_df.index.name = 'testset'
    blast_df.index.name = 'testset'
    with open("source_data/features/GVHoP_GVOGs_all.tsv", 'r') as f:
        wanted_columns = f.readline().strip().split('\t')
    hmm_df = hmm_df.reindex(columns=wanted_columns, fill_value=0)
    with open("source_data/features/GVHoP_GVEUKs_all.tsv", 'r') as f:
        wanted_columns = f.readline().strip().split('\t')
    blast_df = blast_df.reindex(columns=wanted_columns, fill_value=0)


    # Create the dictionary for saving the raw scores
    prob_out_dict = defaultdict(list)

    """ clf_GVOGs """
    # Select the samples
    hmm_df = hmm_df.reindex(sample_ls, fill_value=0)
    # Save the dataframe for future use
    os.makedirs(f"{out_dir}/FeatureSets/", exist_ok=True)
    hmm_df.to_csv(f"{out_dir}/FeatureSets/GVOGs_all.tsv", sep='\t', index=True, header=True)
    # Select GVHoP top features
    top_feature_cols = open("source_data/features/GVHoP_GVOGs_top.tsv").readline().strip().split('\t')
    top_GVOGs_df = hmm_df.reindex(columns=top_feature_cols, fill_value=0)
    # Save the dataframe for future use
    top_GVOGs_df.to_csv(f"{out_dir}/FeatureSets/GVOGs_top.tsv", sep='\t', index=True, header=True)
    # Create a dataframe for saving probability
    prob_out = pd.DataFrame({'testset': sample_ls})
    # Load model
    print("Initialize clf_GVOGs...")
    # Suppress warnings before loading the model, back to normal with "default" setting.
    warnings.filterwarnings('ignore', category=UserWarning)
    for i in range(1, 101):
        ## clf_top ##
        print(f"clf_GVOGs_top_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVOGs/top/XGB_{i}.joblib")
        host_ls = [f"gc_s_{host}" for host in top_ls]
        prob_out_top = run_XGBclf(hmm_df, 8293, model, prob_out, host_ls)
        ## clf_intermediate ##
        print(f"clf_GVOGs_intermediate_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVOGs/intermediate/XGB_{i}.joblib")
        host_ls = [f"gc_s_{host}" for host in intermediate_ls]
        prob_out_intermediate = run_XGBclf(hmm_df, 8293, model, prob_out, host_ls)
        ## clf_bottom ##
        print(f"clf_GVOGs_bottom_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVOGs/bottom/XGB_{i}.joblib")
        host_ls = [f"gc_s_{host}" for host in bottom_ls]
        prob_out_bottom = run_XGBclf(hmm_df, 8293, model, prob_out, host_ls)
        #
        prob_out_dfs = [prob_out_top, prob_out_intermediate, prob_out_bottom]
        # merge the dataframes on the testset
        prob_out_new = reduce(lambda left, right: pd.merge(left, right, on='testset', how='outer'), prob_out_dfs)
        prob_out_dict[i].append(prob_out_new)
    print("Finish clf_GVOGs!")

    """ clf_GVEUKs """
    # Select the samples
    blast_df = blast_df.reindex(sample_ls, fill_value=0)
    # Save the dataframe for future use
    blast_df.to_csv(f"{out_dir}/FeatureSets/GVEUKs_all.tsv", sep='\t', index=True, header=True)
    # Select GVHoP top features
    top_feature_cols = open("source_data/features/GVHoP_GVEUKs_top.tsv").readline().strip().split('\t')
    top_GVEUKs_df = blast_df.reindex(columns=top_feature_cols, fill_value=0)
    # Save the dataframe for future use
    top_GVEUKs_df.to_csv(f"{out_dir}/FeatureSets/GVEUKs_top.tsv", sep='\t', index=True, header=True)
    # Create a dataframe for saving probability
    prob_out = pd.DataFrame({'testset': sample_ls})
    # Load model
    print("Initialize clf_GVEUKs...")
    # Suppress warnings before loading the model, back to normal with "default" setting.
    warnings.filterwarnings('ignore', category=UserWarning)
    for i in range(1, 101):
        ## clf_top ##
        print(f"clf_GVEUKs_top_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVEUKs/top/XGB_{i}.joblib")
        host_ls = [f"hgt_s_{host}" for host in top_ls]
        prob_out_top = run_XGBclf(blast_df, 57250, model, prob_out, host_ls)
        ## clf_intermediate ##
        print(f"clf_GVEUKs_intermediate_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVEUKs/intermediate/XGB_{i}.joblib")
        host_ls = [f"hgt_s_{host}" for host in intermediate_ls]
        prob_out_intermediate = run_XGBclf(blast_df, 57250, model, prob_out, host_ls)
        ## clf_bottom ##
        print(f"clf_GVEUKs_bottom_{i}_model")
        model = joblib.load(f"XGBclf/clf_GVEUKs/bottom/XGB_{i}.joblib")
        host_ls = [f"hgt_s_{host}" for host in bottom_ls]
        prob_out_bottom = run_XGBclf(blast_df, 57250, model, prob_out, host_ls)
        #
        prob_out_dfs = [prob_out_top, prob_out_intermediate, prob_out_bottom]
        # merge the dataframes on the testset
        prob_out_new = reduce(lambda left, right: pd.merge(left, right, on='testset', how='outer'), prob_out_dfs)
        prob_out_dict[i].append(prob_out_new)
    print("Finish clf_GVEUKs!")

    """ GVHoP_clf_integration """
    # Integrate the feature sets
    top_feat = top_GVOGs_df.merge(top_GVEUKs_df, on='testset', how='left')
    for sample, dfs in prob_out_dict.items():
        meta_df_RawScores = dfs[0].merge(dfs[1], on="testset", how="left")
        meta_df_feat = meta_df_RawScores.merge(top_feat, on="testset", how="left")
        prob_out_dict[sample] = meta_df_feat
    meta_df = pd.concat(prob_out_dict.values(), ignore_index=True)
    #
    # Get feature arrays
    FEATURES = meta_df.columns[1:]
    labels = bottom_ls
    n_classes_global = 21
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Initialize meta-model... ")
    # 0. load GVMAGs testing set
    X_test = meta_df[FEATURES]
    #
    # 1. Load the preprocessor back into memory
    loaded_preprocessor = joblib.load("NNclf/preprocessor_all.joblib")
    #
    # 2. Transform new data (CRITICAL: Use .transform(), NOT .fit_transform())
    X_test_scaled = loaded_preprocessor.transform(X_test)
    X_test_scaled[np.isnan(X_test_scaled)] = 0
    #
    # 3. make a df to store the data
    prob_out = pd.DataFrame(meta_df["testset"])
    #
    # 4. load dataset
    test_dataset = torch.tensor(X_test_scaled, dtype=torch.float32)
    safe_sampler = SafeBatchSampler(test_dataset, batch_size=8, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_sampler=safe_sampler, num_workers=2, pin_memory=True)
    #
    # 5. initiate same model architecture
    model_path = "NNclf/nn_all.pt"
    model = MetaNN(n_classes=n_classes_global)
    checkpoint = torch.load(model_path, weights_only=True, map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint)
    model.to(device)
    #
    # 6. CRITICAL: Set the model to evaluation mode
    model.eval()
    probs = []
    preds = []
    with torch.no_grad():
        for xb in test_loader:
            xb = xb.to(device)
            logits = model(xb)
            # Apply Softmax to convert logits to probabilities
            probabilities = torch.softmax(logits, dim=1)
            probs.append(probabilities.cpu().numpy())
            predictions = torch.argmax(logits, dim=1)
            preds.append(predictions.cpu().numpy())
    prob_out["pred_label"] = np.concatenate(preds)
    prob_out[labels] = np.vstack(probs)
    prob_out.to_csv(f"{out_dir}prob_all.tsv", sep="\t", index=False, header=True)
    print("Finish meta-model! ")

    """ Get prediction hierarchy """
    hierarch_list = [['Metazoa', 'Vertebrate', 'Aves'], ['Algae', 'Chlorophyta', 'Chlorellaceae'], ['Amoeba', 'Amoebozoa', 'Discosea'], ['Heteroflagellate', 'Amoeboid', 'Discoba'], ['Algae', 'Chlorophyta', 'Otherchlorophyta'], ['Algae', 'Haptophyta', 'Coccolithophyceae'], ['Algae', 'Haptophyta', 'Otherhaptophyta'], ['Metazoa', 'Vertebrate', 'Mammalia'], ['Heteroflagellate', 'Nonamoeboid', 'Choanocafe'], ['Algae', 'Otheralgae', 'Stramenopile'], ['Algae', 'Chlorophyta', 'Bathycoccaceae'], ['Algae', 'Brownalgae', 'Phaeophyceae'], ['Fungi', 'Chytridiomycota', 'Chytridiomycetes'], ['Metazoa', 'Invertebrate', 'Insecta'], ['Metazoa', 'Invertebrate', 'Otherinvertebrate'], ['Amoeba', 'Amoebozoa', 'Tubulinea'], ['Algae', 'Chlorophyta', 'Mamiellaceae'], ['Metazoa', 'Vertebrate', 'Othervertebrate'], ['Fungi', 'Blastocladiomycota', 'Blastocladiomycetes'], ['Metazoa', 'Invertebrate', 'Malacostraca'], ['Algae', 'Haptophyta', 'Prymnesiaceae']]
    node_dict = {'Algae': [13, 3, 6, 19, 1, 14, 11, 18, 17], 'Chlorophyta': [13, 3, 1, 11], 'Otherchlorophyta': [13], 'Chlorellaceae': [3], 'Fungi': [5, 2], 'Chytridiomycota': [5], 'Chytridiomycetes': [5], 'Metazoa': [12, 10, 16, 15, 0, 9], 'Vertebrate': [12, 16, 0], 'Mammalia': [12], 'Invertebrate': [10, 15, 9], 'Malacostraca': [10], 'Othervertebrate': [16], 'Amoeba': [20, 8], 'Amoebozoa': [20, 8], 'Tubulinea': [20], 'Haptophyta': [6, 14, 18], 'Coccolithophyceae': [6], 'Heteroflagellate': [7, 4], 'Amoeboid': [7], 'Discoba': [7], 'Otheralgae': [19], 'Stramenopile': [19], 'Bathycoccaceae': [1], 'Otherhaptophyta': [14], 'Mamiellaceae': [11], 'Nonamoeboid': [4], 'Choanocafe': [4], 'Otherinvertebrate': [15], 'Blastocladiomycota': [2], 'Blastocladiomycetes': [2], 'Prymnesiaceae': [18], 'Discosea': [8], 'Aves': [0], 'Insecta': [9], 'Brownalgae': [17], 'Phaeophyceae': [17]}
    # bottom-up
    prob_out_levels_BU = climbing_inference(prob_out, hierarch_list, node_dict, 0.75)
    prob_out_levels_BU.to_csv(f"{out_dir}h_prob_all.tsv", sep="\t", index=False, header=True)

    # Create a dictionary for storing predictions
    all_pred_BU = defaultdict(dict)
    sorted_hierarch_list = sorted(hierarch_list)
    flat_hierarch_list = flatten_nested(sorted_hierarch_list)
    for label in flat_hierarch_list:
        for id in sample_ls:
            all_pred_BU[id][label] = 0
    ## add a root
    for id in sample_ls:
        all_pred_BU[id]["root"] = 0
    
    # Create a dictionary for storing predictions of listed samples
    samples_pred_BU = defaultdict(lambda: defaultdict(dict))
    rev_hierarch_list = [sublist[::-1] for sublist in sorted_hierarch_list]
    for i in range(len(hierarch_list[0])):
        labels = [sublist[i] for sublist in rev_hierarch_list]
        for id in set(prob_out["testset"]): ##sample_ids
            for label in labels:
                samples_pred_BU[id][i][label] = 0
		
    # Count predictions
    count_predictions_BU(prob_out_levels_BU, all_pred_BU, samples_pred_BU)

    """ Output counts by levels """
    by_level = defaultdict(dict)
    for sample_id in samples_pred_BU:
        for level in samples_pred_BU[sample_id]:
            by_level[level][sample_id] = samples_pred_BU[sample_id][level]
    # Save each k to a file
    for level, data in by_level.items():
        df = pd.DataFrame(data).T
        df.to_csv(f"{out_dir}pred_out_level{level}.tsv", sep='\t', index=True, header=True)

if __name__ == '__main__':
	main()